# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Merge to Main
on:
  push:
    branches:
      - main

env:
  ADMIN_APP_VERSION: AdminApp.Web-${{ github.sha }}
  ADMIN_DB_VERSION: AdminApp.Database-${{ github.sha }}
  ADMIN_API_VERSION: Admin.Api-${{ github.sha }}
  API_URL: https://api.github.com/repos/${{ github.repository }}
  TOKEN: ${{ secrets.EDFI_BUILD_AGENT_PAT }}

jobs:
  create-pre-releases:
    name: Create Pre-Releases
    runs-on: ubuntu-latest
    steps:
      - name: Set Version Numbers
        shell: pwsh
        run: |
          # Install the MinVer CLI tool
          &dotnet tool install --global minver-cli

      - name: Create Admin App Web Pre-Release
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            ${{ env.API_URL }}/releases \
            -d '{"tag_name":"${{ env.ADMIN_APP_VERSION }}","target_commitish":"main","name":"${{ env.ADMIN_APP_VERSION }}","body":"","draft":false,"prerelease":true,"generate_release_notes":false}'

      - name: Create Admin App Database Pre-Release
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            ${{ env.API_URL }}/releases \
            -d '{"tag_name":"${{ env.ADMIN_DB_VERSION }}","target_commitish":"main","name":"${{ env.ADMIN_DB_VERSION }}","body":"","draft":false,"prerelease":true,"generate_release_notes":false}'

      - name: Create Admin API Pre-Release
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            ${{ env.API_URL }}/releases \
            -d '{"tag_name":"${{ env.ADMIN_API_VERSION }}","target_commitish":"main","name":"${{ env.ADMIN_API_VERSION }}","body":"","draft":false,"prerelease":true,"generate_release_notes":false}'
